os:
  - linux
sudo: false
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$(pwd)/flutter/bin:$PATH"
  - flutter doctor
  - flutter packages get
  - flutter pub global activate dart_coveralls
  - chmod +x tool/travis.sh
script: ./tool/travis.sh
cache:
  directories:
    - $HOME/.pub-cache
