name: redux_prism
description: A new Flutter package project.
version: 0.1.0
author: Gildson Bezerra <gildson13@hotmail.com>
homepage: https://github.com/bgildson/redux_prism

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.1
